## 00. PyTorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


# Introduction to tensors

## Creating tensors

PyTorch tensors are created using `torch.Tensor` -= https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# You can think of dimensions as however many square brackets there are
vector.ndim

1

In [8]:
# You can think of the shape as however many pairs are in the tensor
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape
# This means that we have one tensor that is 3 x 3 in shape

torch.Size([1, 3, 3])

## Random Tensors

Why random tensors?

Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.2147, 0.5257, 0.1699, 0.2102],
         [0.2645, 0.9330, 0.0827, 0.3523],
         [0.7486, 0.7599, 0.3231, 0.5549]]])

In [17]:
random_tensor.ndim

3

In [18]:
# Create a raondom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [19]:
# Create a tensor of zeros (These are helpful with masks)
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Create a range of tensors and tensors-like

In [22]:
# Use torch.range() and get deprecated message, use torch.arrange()
torch.arange(0, 10)
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               # These are very important when you're defining tensors
                               dtype=None,          # What datatype is the tensor (eg float32, float16)
                               device=None,         # What device is your tensor on
                               requires_grad=False)  # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor  # This works because they're both floats

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.long)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 72.])

## Getting information from tensors - Attributes

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shapre from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [29]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1589, 0.9999, 0.6319, 0.0055],
        [0.5225, 0.3630, 0.7926, 0.9536],
        [0.6633, 0.1372, 0.4608, 0.9340]])

In [30]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Shape of tensor: {some_tensor.device}")

tensor([[0.1589, 0.9999, 0.6319, 0.0055],
        [0.5225, 0.3630, 0.7926, 0.9536],
        [0.6633, 0.1372, 0.4608, 0.9340]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Shape of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Tryout PyTorch built-in fuctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix multiplication

Two main way of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matricies - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> The resulting shape in (2,2)
* `(3,2) @ (2,3)` -> The resulting shape in (3,3)

In [45]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4002, 0.5440, 0.2151],
        [0.6407, 0.9963, 0.3451],
        [0.2547, 0.5641, 0.1382]])

In [37]:
# Elemnent wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
tensor

tensor([1, 2, 3])

In [41]:
#Matrix multiplication by hand for tensor * tensor expression
1 * 1 + 2 * 2 + 3 * 3

14

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(12)
CPU times: user 1.5 ms, sys: 0 ns, total: 1.5 ms
Wall time: 2.92 ms


In [44]:
# Use the built in functions! They're vectorized and faster
%%time
torch.matmul(tensor, tensor)

CPU times: user 618 µs, sys: 0 ns, total: 618 µs
Wall time: 629 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

In [47]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,  2],
                         [3,  4],
                         [5,  6]])
tensor_B = torch.tensor([[7,  10],
                         [8,  11],
                         [9,  12]])
# torch.mm(tensor_A, tensor_B) torch.mm is the same thing as matmul (it's as alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulte the shape of one of our tensors using a **transpose**

A **transpose** switches the axes of dimensions of a given tensor.

In [52]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [53]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [55]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Ouput:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Ouput:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
