##00. PyTorch Fundamentals Exercises

---


###1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

*The documentation on torch.Tensor.

*The documentation on torch.cuda.

###2. Create a random tensor with the shape (7,7)

In [ ]:
import torch
tensor1 = torch.rand(size=(7,7))
tensor1, tensor1.shape

(tensor([[0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
         [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
         [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
         [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
         [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313],
         [0.3227, 0.0162, 0.2137, 0.6249, 0.4340, 0.1371, 0.5117],
         [0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998, 0.5944]]),
 torch.Size([7, 7]))

###3. Perform a matrix mulitplication on the tensor from 2 with another random tensor with shape (1,7)

In [ ]:
tensor2 = torch.rand(size=(1,7))
tensor2, tensor2.shape

(tensor([[0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600, 0.2846]]),
 torch.Size([1, 7]))

In [ ]:
tensor3 = torch.matmul(tensor1, tensor2.T)
tensor3, tensor3.shape

(tensor([[0.7967],
         [0.8966],
         [0.9429],
         [1.0652],
         [0.7470],
         [0.8615],
         [0.4998]]),
 torch.Size([7, 1]))

###4. Set the random seed to 0 and do 2 & 3 over again

In [ ]:
torch.manual_seed(0)
tensor_A = torch.rand(7, 7)

torch.manual_seed(0)
tensor_B = torch.rand(1, 7)

tensor_c = torch.matmul(tensor_A, tensor_B.T)

tensor_c, tensor_c.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))