##00. PyTorch Fundamentals Exercises

---


###1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

*The documentation on torch.Tensor.

*The documentation on torch.cuda.

###2. Create a random tensor with the shape (7,7)

In [2]:
import torch
tensor1 = torch.rand(size=(7,7))
tensor1, tensor1.shape

(tensor([[0.9314, 0.2944, 0.7141, 0.1973, 0.7815, 0.8162, 0.8662],
         [0.5511, 0.1444, 0.8717, 0.0572, 0.4391, 0.4243, 0.4067],
         [0.0726, 0.7882, 0.3040, 0.9923, 0.3814, 0.0710, 0.2240],
         [0.7260, 0.8480, 0.7743, 0.7247, 0.3193, 0.4717, 0.9759],
         [0.2607, 0.3002, 0.4945, 0.3274, 0.1681, 0.0162, 0.2735],
         [0.0329, 0.3043, 0.2714, 0.6302, 0.8037, 0.0040, 0.6615],
         [0.3232, 0.8346, 0.8890, 0.9288, 0.7278, 0.2114, 0.4994]]),
 torch.Size([7, 7]))

###3. Perform a matrix mulitplication on the tensor from 2 with another random tensor with shape (1,7)

In [3]:
tensor2 = torch.rand(size=(1,7))
tensor2, tensor2.shape

(tensor([[0.9412, 0.6003, 0.3452, 0.2608, 0.1067, 0.3294, 0.2326]]),
 torch.Size([1, 7]))

In [4]:
tensor3 = torch.matmul(tensor1, tensor2.T)
tensor3, tensor3.shape

(tensor([[1.9051],
         [1.2025],
         [1.0214],
         [2.0651],
         [0.7686],
         [0.7126],
         [1.6179]]),
 torch.Size([7, 1]))

###4. Set the random seed to 0 and do 2 & 3 over again

In [22]:
torch.manual_seed(0)

tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

tensor_c = torch.matmul(tensor_A, tensor_B.T)

tensor_c, tensor_c.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

##5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [6]:
torch.cuda.manual_seed(1234)

##6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [23]:
torch.cuda.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor_cuda1 = torch.rand(size=(2,3)).to(device)
tensor_cuda1, tensor_cuda1.shape

Device: cuda


(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]], device='cuda:0'),
 torch.Size([2, 3]))

In [24]:
torch.cuda.manual_seed(1234)
tensor_cuda2 = torch.rand(size=(2,3)).to(device)
tensor_cuda2, tensor_cuda2.shape

(tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]], device='cuda:0'),
 torch.Size([2, 3]))

##7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [26]:
combined = torch.matmul(tensor_cuda1, tensor_cuda2.T)
combined, combined.shape

(tensor([[0.3129, 0.4120],
         [1.0651, 0.9143]], device='cuda:0'),
 torch.Size([2, 2]))

##8. Find the maximum and minimum values of the output of 7.

In [28]:
minimum = torch.min(combined)
minimum

tensor(0.3129, device='cuda:0')

In [27]:
maximum = torch.max(combined)
maximum

tensor(1.0651, device='cuda:0')

##9. Find the maximum and minimum index values of the output of 7.

In [29]:
arg_min = torch.argmin(combined)
arg_min

tensor(0, device='cuda:0')

In [30]:
arg_max = torch.argmax(combined)
arg_max

tensor(2, device='cuda:0')

##10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [20]:
torch.manual_seed(7)
rand1 = torch.rand(1, 1, 1, 10)
rand1, rand1.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [31]:
rand2 = rand1.squeeze()
rand2, rand2.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))